apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  selector:
    matchLabels:
      app: logic
  template:
    metadata:
      labels:
        app: logic
    spec:
      containers:
        - image: phisco/logic
          name: logic
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: logic
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: logic
