apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  selector:
    matchLabels:
      app: webapp 
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: phisco/webapp
        name: webapp
        env:
          - name: SA_LOGIC_API_URL
            value: "http://logic"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-lb
spec:
  type: NodePort 
  ports:
  - port: 80
    nodePort: 32000
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp
